### PR TITLE
Switch to IAppConfig, declare api key as sensitive

### PR DESCRIPTION
**Pull request by julien-nc**

### CODE REVIEW

**Comment by marcelklehr** [comment]
Should we add a migration to encrypt the existing value?

**Comment by julien-nc** [comment]
@marcelklehr AppConfig encrypts values marked as sensitive.

**Comment by marcelklehr** [comment]
Right, but as-is, these changes only introduce the encryption for the app once the setting is changed if it's already installed, no?

**Comment by julien-nc** [comment]
I'll add a migration step. I made it like that because the API key is not so sensitive as it is necessarily exposed to the frontend. Also the maptiler API keys can be restricted to a specific "Origin" so it's not that bad if they leak.

But yeah, better be clean and consistent. I'll add a migration step in this PR.

**Pull request merged**
